# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

executors:
  default:
    docker:
      - image: cimg/openjdk:14.0

    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build:
    executor: default

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    executor: default

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle check

      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  package:
    executor: default

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle jar
      - store_artifacts:
          path: build/libs/EasyStateMachine-1.0.jar

  deploy:
    executor: default

    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo $mavenUsername $mavenPassword
      - run: gradle publish

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - package
      - deploy:
          requires:
            - hold